spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/demo}
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USERNAME:demo}
    password: ${DATABASE_PASSWORD:}
    hikari:
      connection-timeout: 250
      validation-timeout: 250
      maximum-pool-size: 10
      minimum-idle: 2
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    open-in-view: false

management:
  endpoint:
    health:
      # Only show details to authorized users in production
      show-details: when_authorized
      show-components: when_authorized
